@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String imageTag = "v{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}"

imagePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}', feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/prometheus-adapter:' + imageTag ): 'olcne/prometheus-adapter:' + imageTag],
        platforms: [ 'ol9'],
        architectures: ['x86_64', 'aarch64'],
        buildScript: "sh olm/build-image.sh",
)
