@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String imageTag = "v{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}"

imagePipeline(
        branchPattern: new BranchPattern(master: 'oracle/release/{{{ .major }}}.{{{ .minor }}}.{{{ .patch }}}', feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/prometheus-adapter:' + imageTag ): 'olcne/prometheus-adapter:' + imageTag],
        platforms: [ 'ol9'],
        yumOL9Repos: ['ol9_appstream'],
        buildScript: "sh olm/build-image.sh",
)
